# Generated by Django 5.2.1 on 2025-05-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_create_initial_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='name',
        ),
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Depreciation rate in %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
