# Generated by Django 5.2.1 on 2025-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_remove_asset_name_asset_condition_asset_depreciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_no',
            field=models.CharField(default='TEMP-ASSET-0000', editable=False, max_length=50, unique=True),
        ),
    ]
